import type {
  ClientDocumentRequestInput,
  ClientOrganisation,
  ClientProperty,
  ClientRequestSummary,
} from '../types/clientPortal.js';

function escapeHtml(value: string): string {
  return value
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;')
    .replaceAll("'", '&#039;');
}

function propertyAddress(property?: ClientProperty): string {
  if (!property) return 'Not specified';
  return [
    property.unit ? `${property.unit}, ${property.streetAddress}` : property.streetAddress,
    `${property.suburb} ${property.state} ${property.postcode}`,
  ].join(', ');
}

function section(title: string, value?: string): string {
  if (!value?.trim()) return '';
  return `
    <tr>
      <td style="padding:8px 10px;font-weight:700;width:30%;vertical-align:top;">${escapeHtml(title)}</td>
      <td style="padding:8px 10px;vertical-align:top;">${escapeHtml(value)}</td>
    </tr>`;
}

export function generateDocumentDraft(params: {
  request: ClientRequestSummary;
  input: ClientDocumentRequestInput;
  organisation: ClientOrganisation;
  property?: ClientProperty;
}): { fileName: string; contentType: string; bytes: Buffer } {
  const { request, input, organisation, property } = params;
  const title = input.documentType === 'Other'
    ? input.title?.trim() || 'Property Document'
    : input.documentType;

  const body = `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <title>${escapeHtml(title)} - Draft</title>
</head>
<body style="font-family:Arial,Helvetica,sans-serif;color:#1A2B4A;line-height:1.55;max-width:820px;margin:40px auto;padding:0 28px;">
  <div style="border-bottom:4px solid #00B5B8;padding-bottom:16px;margin-bottom:24px;">
    <div style="font-size:12px;font-weight:700;letter-spacing:.12em;color:#007F82;text-transform:uppercase;">ProInspect</div>
    <h1 style="font-size:28px;margin:8px 0 0;">${escapeHtml(title)}</h1>
    <div style="margin-top:8px;font-size:13px;color:#64748b;">Request reference: ${escapeHtml(request.id)}</div>
  </div>

  <div style="border:2px solid #f59e0b;background:#fffbeb;padding:14px 16px;border-radius:8px;margin-bottom:24px;">
    <strong>DRAFT - REVIEW REQUIRED</strong><br />
    <span style="font-size:13px;">This document was generated from client-supplied information as a working draft. It must be reviewed and approved before issue or execution.</span>
  </div>

  <h2 style="font-size:18px;">Parties and property</h2>
  <table style="border-collapse:collapse;width:100%;background:#f8fafc;border:1px solid #e2e8f0;margin-bottom:24px;">
    ${section('Client / Landlord', organisation.name)}
    ${section('Property', propertyAddress(property))}
    ${section('Counterparty / Recipient', input.counterpartyName)}
  </table>

  <h2 style="font-size:18px;">Requested terms and instructions</h2>
  <table style="border-collapse:collapse;width:100%;background:#f8fafc;border:1px solid #e2e8f0;margin-bottom:24px;">
    ${section('Document type', input.documentType)}
    ${section('Commencement date', input.commencementDate)}
    ${section('Term', input.term)}
    ${section('Rent / consideration', input.rent)}
    ${section('Permitted use', input.permittedUse)}
    ${section('Due date', input.dueDate)}
    ${section('Special conditions', input.specialConditions)}
    ${section('Instructions', input.instructions)}
  </table>

  <h2 style="font-size:18px;">Drafting note</h2>
  <p style="font-size:14px;color:#334155;">
    This draft records the information provided through the ProInspect Client Portal.
    Any clauses, statutory requirements, disclosure obligations, execution requirements
    or specialist legal provisions not expressly included in the client instructions
    remain subject to review before the document is issued.
  </p>

  <div style="margin-top:38px;padding-top:16px;border-top:1px solid #e2e8f0;font-size:12px;color:#64748b;">
    Generated by ProInspect Client Portal · ${escapeHtml(new Date().toISOString())}
  </div>
</body>
</html>`;

  const safeTitle = title.replace(/[^A-Za-z0-9 -]+/g, '').trim() || 'Document';
  return {
    fileName: `${safeTitle} - Draft.html`,
    contentType: 'text/html',
    bytes: Buffer.from(body, 'utf8'),
  };
}
