import type {
  ClientDocumentRequestInput,
  ClientOrganisation,
  ClientProperty,
  ClientRequestSummary,
} from '../types/clientPortal.js';

function escapeHtml(value: string): string {
  return value
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;')
    .replaceAll("'", '&#039;');
}

function propertyAddress(property?: ClientProperty): string {
  if (!property) return 'Not specified';
  return [
    property.unit ? `${property.unit}, ${property.streetAddress}` : property.streetAddress,
    `${property.suburb} ${property.state} ${property.postcode}`,
  ].join(', ');
}

function section(title: string, value?: string): string {
  if (!value?.trim()) return '';
  return `
    <tr>
      <td style="padding:8px 10px;font-weight:700;width:30%;vertical-align:top;">${escapeHtml(title)}</td>
      <td style="padding:8px 10px;vertical-align:top;">${escapeHtml(value)}</td>
    </tr>`;
}

export function generateDocumentDraft(params: {
  request: ClientRequestSummary;
  input: ClientDocumentRequestInput;
  organisation: ClientOrganisation;
  property?: ClientProperty;
}): { fileName: string; contentType: string; bytes: Buffer } {
  const { request, input, organisation, property } = params;
  const title = input.documentType === 'Other'
    ? input.title?.trim() || 'Property Document'
    : input.documentType;

  const body = `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <title>${escapeHtml(title)} - Preparation Summary</title>
</head>
<body style="font-family:Arial,Helvetica,sans-serif;color:#1A2B4A;line-height:1.55;max-width:820px;margin:40px auto;padding:0 28px;">
  <div style="border-bottom:4px solid #00B5B8;padding-bottom:16px;margin-bottom:24px;">
    <div style="font-size:12px;font-weight:700;letter-spacing:.12em;color:#007F82;text-transform:uppercase;">ProInspect</div>
    <h1 style="font-size:28px;margin:8px 0 0;">${escapeHtml(title)} – Preparation Summary</h1>
    <div style="margin-top:8px;font-size:13px;color:#64748b;">Request reference: ${escapeHtml(request.id)}</div>
  </div>

  <div style="border:2px solid #f59e0b;background:#fffbeb;padding:14px 16px;border-radius:8px;margin-bottom:24px;">
    <strong>PREPARATION SUMMARY - REVIEW REQUIRED</strong><br />
    <span style="font-size:13px;">This file records client-supplied drafting instructions. It is not the completed legal or statutory document and must not be issued, signed or relied upon as one.</span>
  </div>

  <h2 style="font-size:18px;">Parties and property</h2>
  <table style="border-collapse:collapse;width:100%;background:#f8fafc;border:1px solid #e2e8f0;margin-bottom:24px;">
    ${section('Client / Landlord', organisation.name)}
    ${section('Property', propertyAddress(property))}
    ${section('Counterparty / Recipient', input.counterpartyName)}
  </table>

  <h2 style="font-size:18px;">Requested terms and instructions</h2>
  <table style="border-collapse:collapse;width:100%;background:#f8fafc;border:1px solid #e2e8f0;margin-bottom:24px;">
    ${section('Document type', input.documentType)}
    ${section('Commencement date', input.commencementDate)}
    ${section('Term', input.term)}
    ${section('Rent / consideration', input.rent)}
    ${section('Permitted use', input.permittedUse)}
    ${section('Due date', input.dueDate)}
    ${section('Special conditions', input.specialConditions)}
    ${section('Instructions', input.instructions)}
  </table>

  <h2 style="font-size:18px;">Preparation note</h2>
  <p style="font-size:14px;color:#334155;">
    This preparation summary records information supplied through the ProInspect Client Portal.
    ProInspect must review the request against the applicable approved template, statutory form
    and any required legal or specialist requirements before a completed document is issued.
  </p>

  <div style="margin-top:38px;padding-top:16px;border-top:1px solid #e2e8f0;font-size:12px;color:#64748b;">
    Generated by ProInspect Client Portal · ${escapeHtml(new Date().toISOString())}
  </div>
</body>
</html>`;

  const safeTitle = title.replace(/[^A-Za-z0-9 -]+/g, '').trim() || 'Document';
  return {
    fileName: `${safeTitle} - Preparation Summary.html`,
    contentType: 'text/html',
    bytes: Buffer.from(body, 'utf8'),
  };
}
