import { InspectionService, BusinessSettings } from '../types/booking';

export const DEFAULT_SERVICES: InspectionService[] = [
  {
    id: 'routine-inspection',
    name: 'Routine Inspection',
    categories: ['residential'],
    publicDescription: 'Comprehensive periodic inspection of residential rental property with photo documentation, maintenance checks and compliance overview.',
    duration: 45,
    bufferBefore: 15,
    bufferAfter: 15,
    minimumNoticeHours: 24,
    maxFutureBookingDays: 60,
    active: true,
    publiclyBookable: true,
    order: 1,
    badge: 'Popular',
    iconName: 'ClipboardCheck',
  },
  {
    id: 'property-condition-report',
    name: 'Property Condition Report (PCR)',
    categories: ['residential'],
    publicDescription: 'Detailed photographic incoming condition report for new tenancies compliant with Western Australian residential tenancies legislation.',
    duration: 90,
    bufferBefore: 15,
    bufferAfter: 20,
    minimumNoticeHours: 48,
    maxFutureBookingDays: 60,
    active: true,
    publiclyBookable: true,
    order: 2,
    badge: 'Comprehensive',
    iconName: 'FileSpreadsheet',
  },
  {
    id: 'pre-vacate-inspection',
    name: 'Pre-Vacate Inspection',
    categories: ['residential'],
    publicDescription: 'Pre-departure inspection to document apparent cleaning, damage, maintenance or rectification matters before the final exit inspection.',
    duration: 45,
    bufferBefore: 15,
    bufferAfter: 15,
    minimumNoticeHours: 24,
    maxFutureBookingDays: 60,
    active: true,
    publiclyBookable: true,
    order: 3,
    badge: 'End of tenancy',
    iconName: 'CalendarClock',
  },
  {
    id: 'final-exit-inspection',
    name: 'Final / Exit Inspection',
    categories: ['residential'],
    publicDescription: 'End-of-lease outgoing comparison inspection comparing current condition against the original Property Condition Report.',
    duration: 60,
    bufferBefore: 15,
    bufferAfter: 15,
    minimumNoticeHours: 24,
    maxFutureBookingDays: 60,
    active: true,
    publiclyBookable: true,
    order: 4,
    iconName: 'LogOut',
  },
  {
    id: 'commercial-property-inspection',
    name: 'Commercial Property Inspection',
    categories: ['commercial'],
    publicDescription: 'Scheduled inspection of commercial, retail, office or industrial premises covering general condition, visible maintenance issues, presentation and apparent operational or lease matters requiring follow-up.',
    duration: 120,
    bufferBefore: 20,
    bufferAfter: 20,
    minimumNoticeHours: 48,
    maxFutureBookingDays: 90,
    active: true,
    publiclyBookable: true,
    order: 5,
    badge: 'Commercial',
    iconName: 'Building2',
  },
  {
    id: 'commercial-pre-vacate-make-good-inspection',
    name: 'Commercial Pre-Vacate / Make-Good Inspection',
    categories: ['commercial'],
    publicDescription: 'Pre-vacate inspection of commercial premises to document apparent make-good, cleaning, damage, maintenance and rectification items before handover.',
    duration: 90,
    bufferBefore: 20,
    bufferAfter: 20,
    minimumNoticeHours: 48,
    maxFutureBookingDays: 90,
    active: true,
    publiclyBookable: true,
    order: 6,
    badge: 'Make-good',
    iconName: 'CalendarClock',
  },
  {
    id: 'commercial-final-make-good-inspection',
    name: 'Commercial Final / Make-Good Inspection',
    categories: ['commercial'],
    publicDescription: 'Final commercial vacate inspection to record property condition, review apparent make-good completion and identify outstanding handover or rectification items.',
    duration: 90,
    bufferBefore: 20,
    bufferAfter: 20,
    minimumNoticeHours: 48,
    maxFutureBookingDays: 90,
    active: true,
    publiclyBookable: true,
    order: 7,
    badge: 'Final handover',
    iconName: 'LogOut',
  },
  {
    id: 'building-management-attendance',
    name: 'Building Management Attendance',
    categories: ['strata-building'],
    publicDescription: 'Routine or scheduled attendance for common areas, strata complexes, plant room access, or facility inspections.',
    duration: 60,
    bufferBefore: 15,
    bufferAfter: 15,
    minimumNoticeHours: 24,
    maxFutureBookingDays: 45,
    active: true,
    publiclyBookable: true,
    order: 8,
    iconName: 'ShieldCheck',
  },
  {
    id: 'maintenance-attendance',
    name: 'Maintenance Attendance',
    categories: ['residential', 'commercial', 'strata-building'],
    publicDescription: 'On-site attendance to assess and document a reported maintenance issue and gather information needed to scope or coordinate repairs.',
    duration: 45,
    bufferBefore: 15,
    bufferAfter: 15,
    minimumNoticeHours: 24,
    maxFutureBookingDays: 30,
    active: true,
    publiclyBookable: true,
    order: 9,
    iconName: 'Wrench',
  },
  {
    id: 'completed-works-inspection',
    name: 'Completed Works Inspection',
    categories: ['residential', 'commercial'],
    publicDescription: 'Post-work attendance to photograph completed repairs or maintenance and document whether the reported works appear to have been completed.',
    duration: 30,
    bufferBefore: 15,
    bufferAfter: 15,
    minimumNoticeHours: 24,
    maxFutureBookingDays: 45,
    active: true,
    publiclyBookable: true,
    order: 10,
    badge: 'Post-work',
    iconName: 'ShieldCheck',
  },
  {
    id: 'follow-up-reinspection',
    name: 'Follow-Up / Reinspection',
    categories: ['residential', 'commercial'],
    publicDescription: 'Targeted return inspection to document whether previously identified cleaning, damage, maintenance, make-good or other rectification items have been addressed.',
    duration: 30,
    bufferBefore: 15,
    bufferAfter: 15,
    minimumNoticeHours: 24,
    maxFutureBookingDays: 45,
    active: true,
    publiclyBookable: true,
    order: 11,
    badge: 'Follow-up',
    iconName: 'ClipboardCheck',
  },
  {
    id: 'property-meeting',
    name: 'Property Meeting',
    categories: ['residential', 'commercial', 'strata-building'],
    publicDescription: 'Onsite consultation with owner, property manager, strata representative or contractor to inspect specific property matters.',
    duration: 30,
    bufferBefore: 15,
    bufferAfter: 15,
    minimumNoticeHours: 24,
    maxFutureBookingDays: 30,
    active: true,
    publiclyBookable: true,
    order: 12,
    iconName: 'Users',
  },
  {
    id: 'contractor-access-attendance',
    name: 'Contractor Access Attendance',
    categories: ['residential', 'commercial'],
    publicDescription: 'Operational attendance to facilitate authorised contractor access to a property or commercial premises and record the attendance where required.',
    duration: 60,
    bufferBefore: 15,
    bufferAfter: 15,
    minimumNoticeHours: 24,
    maxFutureBookingDays: 30,
    active: true,
    publiclyBookable: false,
    order: 13,
    badge: 'Client only',
    iconName: 'KeyRound',
  },
  {
    id: 'key-handover-collection',
    name: 'Key Handover / Collection',
    categories: ['residential', 'commercial'],
    publicDescription: 'Collection, delivery or handover of authorised property keys, remotes or access devices at an agreed location.',
    duration: 30,
    bufferBefore: 15,
    bufferAfter: 15,
    minimumNoticeHours: 24,
    maxFutureBookingDays: 30,
    active: true,
    publiclyBookable: false,
    order: 14,
    badge: 'Client only',
    iconName: 'KeyRound',
  },
  {
    id: 'other-custom-appointment',
    name: 'Other / Custom Appointment',
    categories: ['residential', 'commercial', 'strata-building'],
    publicDescription: 'Custom property attendance for operational requirements that are not covered by another listed service.',
    duration: 60,
    bufferBefore: 15,
    bufferAfter: 15,
    minimumNoticeHours: 24,
    maxFutureBookingDays: 45,
    active: true,
    publiclyBookable: true,
    order: 15,
    iconName: 'HelpCircle',
  },
];

export const DEFAULT_SETTINGS: BusinessSettings = {
  timezone: 'Australia/Perth',
  locale: 'en-AU',
  operatingHours: {
    monday: { open: '08:00', close: '17:00', active: true },
    tuesday: { open: '08:00', close: '16:00', active: true },
    wednesday: { open: '08:00', close: '16:00', active: true },
    thursday: { open: '08:00', close: '16:00', active: true },
    friday: { open: '08:00', close: '16:00', active: true },
    saturday: { open: '09:00', close: '12:00', active: false },
    sunday: { open: '09:00', close: '12:00', active: false },
  },
  minimumNoticeHours: 24,
  maxFutureBookingDays: 60,
  calendarConnected: false,
};
