import { InspectionService, BusinessSettings } from '../types/booking';

export const DEFAULT_SERVICES: InspectionService[] = [
  {
    id: 'routine-inspection',
    name: 'Routine Inspection',
    publicDescription: 'Comprehensive periodic inspection of residential rental property with photo documentation, maintenance checks and compliance overview.',
    duration: 45,
    bufferBefore: 15,
    bufferAfter: 15,
    minimumNoticeHours: 24,
    maxFutureBookingDays: 60,
    active: true,
    publiclyBookable: true,
    order: 1,
    badge: 'Popular',
    iconName: 'ClipboardCheck',
  },
  {
    id: 'property-condition-report',
    name: 'Property Condition Report (PCR)',
    publicDescription: 'Detailed photographic incoming condition report for new tenancies compliant with Western Australian residential tenancies legislation.',
    duration: 90,
    bufferBefore: 15,
    bufferAfter: 20,
    minimumNoticeHours: 48,
    maxFutureBookingDays: 60,
    active: true,
    publiclyBookable: true,
    order: 2,
    badge: 'Comprehensive',
    iconName: 'FileSpreadsheet',
  },
  {
    id: 'final-exit-inspection',
    name: 'Final / Exit Inspection',
    publicDescription: 'End-of-lease outgoing comparison inspection comparing current condition against the original Property Condition Report.',
    duration: 60,
    bufferBefore: 15,
    bufferAfter: 15,
    minimumNoticeHours: 24,
    maxFutureBookingDays: 60,
    active: true,
    publiclyBookable: true,
    order: 3,
    iconName: 'LogOut',
  },
  {
    id: 'commercial-property-inspection',
    name: 'Commercial Property Inspection',
    publicDescription: 'Specialist commercial, retail or office property condition and compliance inspection tailored for asset and property managers.',
    duration: 120,
    bufferBefore: 20,
    bufferAfter: 20,
    minimumNoticeHours: 48,
    maxFutureBookingDays: 90,
    active: true,
    publiclyBookable: true,
    order: 4,
    badge: 'Commercial',
    iconName: 'Building2',
  },
  {
    id: 'maintenance-attendance',
    name: 'Maintenance Attendance',
    publicDescription: 'On-site attendance to assess specific maintenance issues, verify trade completion, or scope urgent repair works.',
    duration: 45,
    bufferBefore: 15,
    bufferAfter: 15,
    minimumNoticeHours: 24,
    maxFutureBookingDays: 30,
    active: true,
    publiclyBookable: true,
    order: 5,
    iconName: 'Wrench',
  },
  {
    id: 'property-meeting',
    name: 'Property Meeting',
    publicDescription: 'Onsite consultation with owner, property manager, strata representative or contractor to inspect specific property matters.',
    duration: 30,
    bufferBefore: 15,
    bufferAfter: 15,
    minimumNoticeHours: 24,
    maxFutureBookingDays: 30,
    active: true,
    publiclyBookable: true,
    order: 6,
    iconName: 'Users',
  },
  {
    id: 'building-management-attendance',
    name: 'Building Management Attendance',
    publicDescription: 'Routine or scheduled attendance for common areas, strata complexes, plant room access, or facility inspections.',
    duration: 60,
    bufferBefore: 15,
    bufferAfter: 15,
    minimumNoticeHours: 24,
    maxFutureBookingDays: 45,
    active: true,
    publiclyBookable: true,
    order: 7,
    iconName: 'ShieldCheck',
  },
  {
    id: 'other-custom-appointment',
    name: 'Other / Custom Appointment',
    publicDescription: 'Custom attendance, special scoping visits, key handovers or unique property operational requirements.',
    duration: 60,
    bufferBefore: 15,
    bufferAfter: 15,
    minimumNoticeHours: 24,
    maxFutureBookingDays: 45,
    active: true,
    publiclyBookable: true,
    order: 8,
    iconName: 'HelpCircle',
  },
];

export const DEFAULT_SETTINGS: BusinessSettings = {
  timezone: 'Australia/Perth',
  locale: 'en-AU',
  operatingHours: {
    monday: { open: '08:00', close: '17:00', active: true },
    tuesday: { open: '08:00', close: '16:00', active: true },
    wednesday: { open: '08:00', close: '16:00', active: true },
    thursday: { open: '08:00', close: '16:00', active: true },
    friday: { open: '08:00', close: '16:00', active: true },
    saturday: { open: '09:00', close: '12:00', active: false },
    sunday: { open: '09:00', close: '12:00', active: false },
  },
  minimumNoticeHours: 24,
  maxFutureBookingDays: 60,
  calendarConnected: true,
};
