import { InspectionService, BusinessSettings } from '../types/booking';

export const DEFAULT_SERVICES: InspectionService[] = [
  {
    id: 'routine-inspection',
    name: 'Routine Inspection',
    categories: ['residential'],
    publicDescription: 'Comprehensive periodic inspection of residential rental property with photo documentation, maintenance checks and compliance overview.',
    duration: 45,
    bufferBefore: 15,
    bufferAfter: 15,
    minimumNoticeHours: 24,
    maxFutureBookingDays: 60,
    active: true,
    publiclyBookable: true,
    order: 1,
    badge: 'Popular',
    iconName: 'ClipboardCheck',
  },
  {
    id: 'property-condition-report',
    name: 'Property Condition Report (PCR)',
    categories: ['residential'],
    publicDescription: 'Detailed photographic incoming condition report for new tenancies compliant with Western Australian residential tenancies legislation.',
    duration: 90,
    bufferBefore: 15,
    bufferAfter: 20,
    minimumNoticeHours: 48,
    maxFutureBookingDays: 60,
    active: true,
    publiclyBookable: true,
    order: 2,
    badge: 'Comprehensive',
    iconName: 'FileSpreadsheet',
  },
  {
    id: 'pre-vacate-inspection',
    name: 'Pre-Vacate Inspection',
    categories: ['residential'],
    publicDescription: 'Pre-departure inspection to document apparent cleaning, damage, maintenance or rectification matters before the final exit inspection.',
    duration: 45,
    bufferBefore: 15,
    bufferAfter: 15,
    minimumNoticeHours: 24,
    maxFutureBookingDays: 60,
    active: true,
    publiclyBookable: true,
    order: 3,
    badge: 'End of tenancy',
    iconName: 'CalendarClock',
  },
  {
    id: 'final-exit-inspection',
    name: 'Final / Exit Inspection',
    categories: ['residential'],
    publicDescription: 'End-of-lease outgoing comparison inspection comparing current condition against the original Property Condition Report.',
    duration: 60,
    bufferBefore: 15,
    bufferAfter: 15,
    minimumNoticeHours: 24,
    maxFutureBookingDays: 60,
    active: true,
    publiclyBookable: true,
    order: 4,
    iconName: 'LogOut',
  },
  {
    id: 'commercial-property-inspection',
    name: 'Commercial Property Inspection',
    categories: ['commercial'],
    publicDescription: 'Scheduled inspection of commercial, retail, office or industrial premises covering general condition, visible maintenance issues, presentation and apparent operational or lease matters requiring follow-up.',
    duration: 120,
    bufferBefore: 20,
    bufferAfter: 20,
    minimumNoticeHours: 48,
    maxFutureBookingDays: 90,
    active: true,
    publiclyBookable: true,
    order: 5,
    badge: 'Commercial',
    iconName: 'Building2',
  },
  {
    id: 'commercial-pre-vacate-make-good-inspection',
    name: 'Commercial Pre-Vacate / Make-Good Inspection',
    categories: ['commercial'],
    publicDescription: 'Pre-vacate inspection of commercial premises to document apparent make-good, cleaning, damage, maintenance and rectification items before handover.',
    duration: 90,
    bufferBefore: 20,
    bufferAfter: 20,
    minimumNoticeHours: 48,
    maxFutureBookingDays: 90,
    active: true,
    publiclyBookable: true,
    order: 6,
    badge: 'Make-good',
    iconName: 'CalendarClock',
  },
  {
    id: 'commercial-final-make-good-inspection',
    name: 'Commercial Final / Make-Good Inspection',
    categories: ['commercial'],
    publicDescription: 'Final commercial vacate inspection to record property condition, review apparent make-good completion and identify outstanding handover or rectification items.',
    duration: 90,
    bufferBefore: 20,
    bufferAfter: 20,
    minimumNoticeHours: 48,
    maxFutureBookingDays: 90,
    active: true,
    publiclyBookable: true,
    order: 7,
    badge: 'Final handover',
    iconName: 'LogOut',
  },
  {
    id: 'common-property-inspection',
    name: 'Common Property Inspection',
    categories: ['strata-building'],
    publicDescription: 'Scheduled inspection of common areas, accessways, amenities, parking and external shared areas to document visible condition, maintenance and presentation issues.',
    duration: 60,
    bufferBefore: 15,
    bufferAfter: 15,
    minimumNoticeHours: 24,
    maxFutureBookingDays: 60,
    active: true,
    publiclyBookable: true,
    order: 8,
    badge: 'Common property',
    iconName: 'Building2',
  },
  {
    id: 'building-management-attendance',
    name: 'Building Management Attendance',
    categories: ['strata-building'],
    publicDescription: 'General onsite building-management attendance for common areas, facilities, access matters and other routine operational requirements.',
    duration: 60,
    bufferBefore: 15,
    bufferAfter: 15,
    minimumNoticeHours: 24,
    maxFutureBookingDays: 45,
    active: true,
    publiclyBookable: true,
    order: 9,
    iconName: 'ShieldCheck',
  },
  {
    id: 'maintenance-attendance',
    name: 'Maintenance Attendance',
    categories: ['residential', 'commercial', 'strata-building'],
    publicDescription: 'On-site attendance to assess and document a reported maintenance issue and gather information needed to scope or coordinate repairs.',
    duration: 45,
    bufferBefore: 15,
    bufferAfter: 15,
    minimumNoticeHours: 24,
    maxFutureBookingDays: 30,
    active: true,
    publiclyBookable: true,
    order: 10,
    iconName: 'Wrench',
  },
  {
    id: 'completed-works-inspection',
    name: 'Completed Works Inspection',
    categories: ['residential', 'commercial', 'strata-building'],
    publicDescription: 'Post-work attendance to photograph completed repairs or maintenance and document whether the reported works appear to have been completed.',
    duration: 30,
    bufferBefore: 15,
    bufferAfter: 15,
    minimumNoticeHours: 24,
    maxFutureBookingDays: 45,
    active: true,
    publiclyBookable: true,
    order: 11,
    badge: 'Post-work',
    iconName: 'ShieldCheck',
  },
  {
    id: 'follow-up-reinspection',
    name: 'Follow-Up / Reinspection',
    categories: ['residential', 'commercial', 'strata-building'],
    publicDescription: 'Targeted return inspection to document whether previously identified cleaning, damage, maintenance, make-good, common-property, defect or other rectification items have been addressed.',
    duration: 30,
    bufferBefore: 15,
    bufferAfter: 15,
    minimumNoticeHours: 24,
    maxFutureBookingDays: 45,
    active: true,
    publiclyBookable: true,
    order: 12,
    badge: 'Follow-up',
    iconName: 'ClipboardCheck',
  },
  {
    id: 'damage-incident-inspection',
    name: 'Damage / Incident Inspection',
    categories: ['strata-building'],
    publicDescription: 'Onsite attendance to photograph and document apparent damage, deterioration or an incident affecting common property for further review and action.',
    duration: 45,
    bufferBefore: 15,
    bufferAfter: 15,
    minimumNoticeHours: 12,
    maxFutureBookingDays: 30,
    active: true,
    publiclyBookable: true,
    order: 13,
    badge: 'Incident',
    iconName: 'ShieldCheck',
  },
  {
    id: 'cleaning-presentation-inspection',
    name: 'Cleaning & Presentation Inspection',
    categories: ['strata-building'],
    publicDescription: 'Inspection of common-area cleanliness and presentation to document apparent cleaning deficiencies and areas requiring follow-up.',
    duration: 30,
    bufferBefore: 15,
    bufferAfter: 15,
    minimumNoticeHours: 24,
    maxFutureBookingDays: 30,
    active: true,
    publiclyBookable: true,
    order: 14,
    badge: 'Presentation',
    iconName: 'ClipboardCheck',
  },
  {
    id: 'defect-rectification-inspection',
    name: 'Defect / Rectification Inspection',
    categories: ['strata-building'],
    publicDescription: 'Inspection to document identified building or common-property defects and record the apparent status of rectification items for follow-up.',
    duration: 60,
    bufferBefore: 15,
    bufferAfter: 15,
    minimumNoticeHours: 24,
    maxFutureBookingDays: 45,
    active: true,
    publiclyBookable: true,
    order: 15,
    badge: 'Defects',
    iconName: 'FileSpreadsheet',
  },
  {
    id: 'property-meeting',
    name: 'Property Meeting',
    categories: ['residential', 'commercial', 'strata-building'],
    publicDescription: 'Onsite consultation with owner, property manager, strata representative or contractor to inspect specific property matters.',
    duration: 30,
    bufferBefore: 15,
    bufferAfter: 15,
    minimumNoticeHours: 24,
    maxFutureBookingDays: 30,
    active: true,
    publiclyBookable: true,
    order: 16,
    iconName: 'Users',
  },
  {
    id: 'contractor-access-attendance',
    name: 'Contractor Access Attendance',
    categories: ['residential', 'commercial', 'strata-building'],
    publicDescription: 'Operational attendance to facilitate authorised contractor access to a property, commercial premises or common-property area and record the attendance where required.',
    duration: 60,
    bufferBefore: 15,
    bufferAfter: 15,
    minimumNoticeHours: 24,
    maxFutureBookingDays: 30,
    active: true,
    publiclyBookable: false,
    order: 17,
    badge: 'Client only',
    iconName: 'KeyRound',
  },
  {
    id: 'key-handover-collection',
    name: 'Key / Fob / Remote Handover',
    categories: ['residential', 'commercial', 'strata-building'],
    publicDescription: 'Collection, delivery or handover of authorised property keys, fobs, remotes or other access devices at an agreed location.',
    duration: 30,
    bufferBefore: 15,
    bufferAfter: 15,
    minimumNoticeHours: 24,
    maxFutureBookingDays: 30,
    active: true,
    publiclyBookable: false,
    order: 18,
    badge: 'Client only',
    iconName: 'KeyRound',
  },
  {
    id: 'contractor-supervision-attendance',
    name: 'Contractor Supervision Attendance',
    categories: ['strata-building'],
    publicDescription: 'Onsite operational attendance to remain available while authorised contractors carry out specified works or access shared building areas.',
    duration: 60,
    bufferBefore: 15,
    bufferAfter: 15,
    minimumNoticeHours: 24,
    maxFutureBookingDays: 30,
    active: true,
    publiclyBookable: false,
    order: 19,
    badge: 'Client only',
    iconName: 'Users',
  },
  {
    id: 'move-in-move-out-attendance',
    name: 'Move-In / Move-Out Attendance',
    categories: ['strata-building'],
    publicDescription: 'Operational attendance to coordinate authorised building access, loading areas, lifts and common-property requirements for a move-in or move-out.',
    duration: 60,
    bufferBefore: 15,
    bufferAfter: 15,
    minimumNoticeHours: 48,
    maxFutureBookingDays: 60,
    active: true,
    publiclyBookable: false,
    order: 20,
    badge: 'Client only',
    iconName: 'CalendarClock',
  },
  {
    id: 'urgent-building-attendance',
    name: 'Emergency / Urgent Building Attendance',
    categories: ['strata-building'],
    publicDescription: 'Urgent onsite attendance for an unexpected building or common-property incident requiring an operational representative and documented follow-up.',
    duration: 60,
    bufferBefore: 15,
    bufferAfter: 15,
    minimumNoticeHours: 0,
    maxFutureBookingDays: 7,
    active: true,
    publiclyBookable: false,
    order: 21,
    badge: 'Client only',
    iconName: 'ShieldCheck',
  },
  {
    id: 'building-handover-attendance',
    name: 'Building Handover Attendance',
    categories: ['strata-building'],
    publicDescription: 'Operational handover attendance between building managers, strata representatives, contractors or other authorised parties.',
    duration: 90,
    bufferBefore: 15,
    bufferAfter: 15,
    minimumNoticeHours: 48,
    maxFutureBookingDays: 60,
    active: true,
    publiclyBookable: false,
    order: 22,
    badge: 'Client only',
    iconName: 'Briefcase',
  },
  {
    id: 'other-custom-appointment',
    name: 'Other / Custom Appointment',
    categories: ['residential', 'commercial', 'strata-building'],
    publicDescription: 'Custom property attendance for operational requirements that are not covered by another listed service.',
    duration: 60,
    bufferBefore: 15,
    bufferAfter: 15,
    minimumNoticeHours: 24,
    maxFutureBookingDays: 45,
    active: true,
    publiclyBookable: true,
    order: 23,
    iconName: 'HelpCircle',
  },
];

export const DEFAULT_SETTINGS: BusinessSettings = {
  timezone: 'Australia/Perth',
  locale: 'en-AU',
  operatingHours: {
    monday: { open: '08:00', close: '17:00', active: true },
    tuesday: { open: '08:00', close: '16:00', active: true },
    wednesday: { open: '08:00', close: '16:00', active: true },
    thursday: { open: '08:00', close: '16:00', active: true },
    friday: { open: '08:00', close: '16:00', active: true },
    saturday: { open: '09:00', close: '12:00', active: false },
    sunday: { open: '09:00', close: '12:00', active: false },
  },
  minimumNoticeHours: 24,
  maxFutureBookingDays: 60,
  calendarConnected: false,
};
