import type { TenantFormDefinition } from '../types/tenantForms';

export const TENANT_FORM_DEFINITIONS: TenantFormDefinition[] = [
  {
    id: 'form-24-furniture-safety',
    workflowType: 'furniture_safety',
    formCode: '24',
    name: 'Request to lessor to affix furniture',
    shortName: 'Furniture Safety',
    description: 'Request permission to affix furniture to a wall for the safety of a child or a person with a disability.',
    officialSourceUrl: 'https://www.consumerprotection.wa.gov.au/publications/request-lessor-affix-furniture-form-24',
    officialTemplateUrl: 'https://www.consumerprotection.wa.gov.au/system/files/documents/2025-07/requestaffixfurnitureform24.pdf',
    officialVersion: 'July 2024',
    responseDays: 14,
    sensitive: false,
    active: true,
    category: 'request',
    clientApproval: true,
    responseRule: 'calendar_days_from_delivery',
    expiryBehaviour: 'auto_approved_subject_to_law',
  },
  {
    id: 'form-25-pet-request',
    workflowType: 'pet_request',
    formCode: '25',
    name: 'Pet request',
    shortName: 'Pet Request',
    description: 'Request permission from the landlord to keep a pet at the property.',
    officialSourceUrl: 'https://www.consumerprotection.wa.gov.au/publications/pet-request-form-form-25',
    officialVersion: 'July 2024',
    responseDays: 14,
    sensitive: false,
    active: true,
    category: 'request',
    clientApproval: true,
    responseRule: 'calendar_days_from_delivery',
    expiryBehaviour: 'auto_approved_subject_to_law',
  },
  {
    id: 'form-26-minor-modification',
    workflowType: 'minor_modification',
    formCode: '26',
    name: 'Minor modification request',
    shortName: 'Minor Modification',
    description: 'Request permission to make a minor modification to the rental property.',
    officialSourceUrl: 'https://www.consumerprotection.wa.gov.au/publications/minor-modification-request-form-form-26',
    officialVersion: 'July 2024',
    responseDays: 14,
    sensitive: false,
    active: true,
    category: 'request',
    clientApproval: true,
    responseRule: 'calendar_days_from_delivery',
    expiryBehaviour: 'auto_approved_subject_to_law',
  },
  {
    id: 'form-27-major-modification',
    workflowType: 'major_modification',
    formCode: '27',
    name: 'Request to landlord (lessor) to make major modification',
    shortName: 'Major Modification',
    description: 'Request permission to make a major modification that is not a minor, furniture-safety or family-violence security modification.',
    officialSourceUrl: 'https://www.consumerprotection.wa.gov.au/publications/request-landlord-lessor-make-major-modification-form-27',
    officialTemplateUrl: 'https://www.consumerprotection.wa.gov.au/system/files/documents/2026-05/majormodificationlandlordform27.pdf',
    officialVersion: 'July 2024',
    responseDays: 28,
    sensitive: false,
    active: true,
    category: 'request',
    clientApproval: true,
    responseRule: 'calendar_days_from_delivery',
    expiryBehaviour: 'none',
  },
  {
    id: 'security-bond-release',
    workflowType: 'bond_release',
    formCode: 'BOND-RELEASE',
    name: 'Security Bond Release Application',
    shortName: 'Bond Release',
    description: 'Prepare a security bond release request and capture proposed payments and claims for official lodgement.',
    officialSourceUrl: 'https://www.consumerprotection.wa.gov.au/publications/security-bond-release-application',
    officialTemplateUrl: 'https://www.consumerprotection.wa.gov.au/system/files/documents/2026-03/SecurityBondReleaseAppform0326.pdf',
    officialVersion: 'March 2026',
    responseDays: 14,
    sensitive: false,
    active: true,
    category: 'bond',
    clientApproval: false,
    responseRule: 'calendar_days_from_receipt',
    expiryBehaviour: 'none',
  },
  {
    id: 'security-bond-variation',
    workflowType: 'bond_variation',
    formCode: 'BOND-VARIATION',
    name: 'Variation of Security Bond',
    shortName: 'Change Bond Details',
    description: 'Request a change to tenant or bond details and prepare the information required for BondsOnline or the official manual process.',
    officialSourceUrl: 'https://www.consumerprotection.wa.gov.au/publications/variation-security-bond',
    officialVersion: 'Current official version',
    sensitive: false,
    active: true,
    category: 'bond',
    clientApproval: false,
    expiryBehaviour: 'none',
  },
  {
    id: 'form-1-pcr-response',
    workflowType: 'pcr_response',
    formCode: '1',
    name: 'Property Condition Report tenant response',
    shortName: 'Review Entry Condition Report',
    description: 'Review the entry Property Condition Report, record agreement or disagreement and add tenant comments/evidence.',
    officialSourceUrl: 'https://www.consumerprotection.wa.gov.au/publications/property-condition-report-form-1',
    officialVersion: 'Current prescribed Form 1',
    tenantResponseDays: 7,
    sensitive: false,
    active: true,
    category: 'inspection',
    clientApproval: false,
    responseRule: 'calendar_days_from_delivery',
    expiryBehaviour: 'none',
  },
  {
    id: 'form-2-family-violence',
    workflowType: 'family_violence_termination',
    formCode: '2',
    name: 'Notice of termination of tenant’s interest on grounds of family violence',
    shortName: 'Private Tenancy Support',
    description: 'Restricted workflow for a tenant ending their interest in a tenancy on family-violence grounds.',
    officialSourceUrl: 'https://www.consumerprotection.wa.gov.au/publications/notice-termination-tenants-interest-residential-tenancy-agreement-grounds-family',
    sensitive: true,
    active: true,
    category: 'sensitive',
    clientApproval: false,
    expiryBehaviour: 'none',
  },
];

export function getTenantFormDefinition(id: string): TenantFormDefinition | undefined {
  return TENANT_FORM_DEFINITIONS.find((definition) => definition.id === id && definition.active);
}
