import test from 'node:test';
import assert from 'node:assert/strict';
import { inspectPlan } from '../infra.mjs';
import { deploymentConfig } from '../deploy-staging.mjs';
const target={environment:'staging',project:'proinspect-staging-test'};
const plan=changes=>({variables:{environment:{value:target.environment},project_id:{value:target.project}},resource_changes:changes});
const change=(type,actions,after={})=>({type,address:`${type}.test`,change:{actions,after}});
test('Terraform deletions and replacements are rejected',()=>{ assert.ok(inspectPlan(plan([change('google_storage_bucket',['delete'],null)]),target).length);assert.ok(inspectPlan(plan([change('google_firestore_database',['delete','create'])]),target).length); });
test('Cloud Run service and secret payload/key ownership are rejected',()=>{ for(const type of ['google_cloud_run_v2_service','google_cloud_run_service','google_secret_manager_secret_version','google_service_account_key'])assert.ok(inspectPlan(plan([change(type,['create'])]),target).length); });
test('Public buckets and authoritative IAM are rejected',()=>{ for(const c of [change('google_storage_bucket',['create'],{uniform_bucket_level_access:false}),change('google_project_iam_binding',['update']),change('google_project_iam_member',['create'],{member:'allUsers'})]) assert.ok(inspectPlan(plan([c]),target).length); });
test('Safe additive infrastructure plan accepted',()=>{ assert.deepEqual(inspectPlan(plan([change('google_storage_bucket',['create'],{uniform_bucket_level_access:true,public_access_prevention:'enforced',force_destroy:false}),change('google_project_iam_member',['create'],{member:'serviceAccount:test'})]),target),[]); });
test('Terraform saved-plan target cannot be substituted',()=>{ assert.ok(inspectPlan(plan([]),{...target,project:'other-project'}).length); });
function config(){return {environment:'staging',project_id:target.project,production_project_id:'business-plan-applicatio-17047',region:'australia-southeast1',service_name:'proinspect-staging',database_id:'stage3',runtime_service_account:`runtime@${target.project}.iam.gserviceaccount.com`,build_service_account:`build@${target.project}.iam.gserviceaccount.com`,documents_bucket:'staging-docs',source_bucket:'staging-source',image_repository:`australia-southeast1-docker.pkg.dev/${target.project}/platform/platform`,runtime_environment:{APP_URL:'https://staging.example.invalid',PLATFORM_ENVIRONMENT:'staging',EMAIL_DELIVERY_MODE:'disabled',FIREBASE_PROJECT_ID:target.project,FIRESTORE_DATABASE_ID:'stage3',FIREBASE_STORAGE_BUCKET:'staging-docs'},secret_bindings:{ACCESS_DATA_ENCRYPTION_KEY:'proinspect-staging-access-data-encryption-key:1',REPORT_INGEST_TOKEN:'proinspect-staging-report-ingest-token:1',REPORT_HANDOFF_SIGNING_KEY:'proinspect-staging-report-handoff-signing-key:1'}};}
const web={projectId:target.project,firestoreDatabaseId:'stage3',storageBucket:'staging-docs',apiKey:'public-web-key',authDomain:`${target.project}.firebaseapp.com`};
test('Separate staging browser/backend config accepted',()=>{deploymentConfig(config(),web);});
test('Production Firebase browser config cannot be bundled into staging',()=>{assert.throws(()=>deploymentConfig(config(),{...web,projectId:'business-plan-applicatio-17047'}));});
test('Staging rejects latest aliases and plaintext secrets',()=>{const a=config();a.secret_bindings.REPORT_INGEST_TOKEN='proinspect-staging-report-ingest-token:latest';assert.throws(()=>deploymentConfig(a,web));const b=config();b.runtime_environment.RESEND_API_KEY='bad';assert.throws(()=>deploymentConfig(b,web));});
test('Staging rejects production and cross-project identities',()=>{const a=config();a.environment='production';assert.throws(()=>deploymentConfig(a,web));const b=config();b.runtime_service_account='x@production.iam.gserviceaccount.com';assert.throws(()=>deploymentConfig(b,web));});
