import assert from 'node:assert/strict';
import { spawn } from 'node:child_process';
import { once } from 'node:events';
import { writeFileSync } from 'node:fs';
assert.equal(process.env.FIREBASE_PROJECT_ID, 'demo-stage1');
assert.match(process.env.FIRESTORE_EMULATOR_HOST || '', /^(127\.0\.0\.1|localhost):[0-9]+$/);
assert.match(process.env.FIREBASE_AUTH_EMULATOR_HOST || '', /^(127\.0\.0\.1|localhost):[0-9]+$/);
assert.equal(process.env.FIRESTORE_DATABASE_ID, '(default)');
assert.ok(!process.env.GOOGLE_APPLICATION_CREDENTIALS && !process.env.FIREBASE_SERVICE_ACCOUNT_JSON);
const { adminDb: db, adminAuth } = await import('../src/server/firebaseAdmin.js');
const store = await import('../src/server/store.js');
const { randomUUID } = await import('node:crypto');
let checks = 0;
function pass(name: string) { checks++; console.log(`PASS ${checks}: ${name}`); }
async function user(uid: string) {
  const email = `${uid}@stage1.test`;
  await adminAuth.createUser({ uid, email, emailVerified: true, password: 'Stage1-only-test-password!' });
  const response = await fetch(`http://${process.env.FIREBASE_AUTH_EMULATOR_HOST}/identitytoolkit.googleapis.com/v1/accounts:signInWithPassword?key=fixture`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ email, password: 'Stage1-only-test-password!', returnSecureToken: true }) });
  assert.equal(response.status, 200);
  const token = (await response.json() as any).idToken as string;
  return { uid, email, token };
}
const owner = await user('owner');
const other = await user('other');
const viewer = await user('viewer');
const contexts = await Promise.all(Array.from({ length: 4 }, () => store.ensureClientContext(owner)));
assert.equal(new Set(contexts.map(c => c.organisation.id)).size, 1);
const context = contexts[0];
assert.equal((await db.collection('clientMemberships').where('uid', '==', owner.uid).get()).size, 1);
pass('Concurrent first sign-in creates one organisation and one membership');
const otherContext = await store.ensureClientContext(other);
await store.inviteClientOrganisationMember({ context, email: viewer.email, role: 'viewer' });
const viewerContext = await store.ensureClientContext(viewer);
await assert.rejects(store.createClientRequest({ context: viewerContext, type: 'maintenance', title: 'Must not create' }), /CLIENT_WRITE_FORBIDDEN/);
await assert.rejects(store.inviteClientOrganisationMember({ context: viewerContext, email: 'forbidden@stage1.test', role: 'admin' }), /CLIENT_WRITE_FORBIDDEN/);
pass('Viewer cannot create requests or grant membership');
const propertyInput = { streetAddress: '1 Test Street', suburb: 'Perth', state: 'WA', postcode: '6000', propertyType: 'Residential' as any, categories: ['residential' as const] };
const property = await store.createClientProperty({ context, input: propertyInput });
const property2 = await store.createClientProperty({ context, input: { ...propertyInput, streetAddress: '2 Test Street' } });
const request = await store.createClientRequest({ context, type: 'document', title: 'Draft request', propertyId: property.id });
const file = { context, propertyId: property.id, requestId: request.id, name: 'Attachment.pdf', documentType: 'Evidence', status: 'available' as const, storagePath: 'client-files/fixture/test.pdf', contentType: 'application/pdf', sizeBytes: 10 };
await Promise.all(Array.from({ length: 8 }, () => store.createClientDocument(file)));
assert.equal((await store.getClientRequest({ organisationId: context.organisation.id, requestId: request.id }))?.attachmentDocumentIds?.length, 8);
pass('Concurrent attachments are linked atomically without lost file IDs');
await assert.rejects(store.createClientDocument({ ...file, propertyId: property2.id }), /CLIENT_ATTACHMENT_PROPERTY_MISMATCH/);
await assert.rejects(store.createClientDocument({ ...file, context: otherContext }), /CLIENT_REQUEST_FORBIDDEN/);
await assert.rejects(store.createClientDocument({ ...file, context: viewerContext }), /CLIENT_WRITE_FORBIDDEN/);
pass('File relationships and cross-organisation/read-only writes are denied');
const attempts = await Promise.allSettled(Array.from({ length: 4 }, () => store.claimClientDocumentDraftGeneration({ context, requestId: request.id })));
const successful = attempts.filter(a => a.status === 'fulfilled');
assert.equal(successful.length, 1);
const firstLease = (successful[0] as PromiseFulfilledResult<any>).value;
await db.collection('clientRequests').doc(request.id).update({ draftGenerationExpiresAt: '2020-01-01T00:00:00.000Z' });
const secondLease = await store.claimClientDocumentDraftGeneration({ context, requestId: request.id });
assert.notEqual(secondLease.draftGenerationToken, firstLease.draftGenerationToken);
await store.releaseClientDocumentDraftGeneration({ context, requestId: request.id, generationToken: firstLease.draftGenerationToken });
assert.equal((await db.collection('clientRequests').doc(request.id).get()).data()?.draftGenerationToken, secondLease.draftGenerationToken);
const publishInput = { context, requestId: request.id, generationToken: secondLease.draftGenerationToken!, name: 'Draft.html', documentType: 'Lease', storagePath: 'client-files/fixture/draft.html', contentType: 'text/html', sizeBytes: 100 };
await assert.rejects(store.completeClientDocumentDraftGeneration({ ...publishInput, generationToken: firstLease.draftGenerationToken }), /CLIENT_DRAFT_LEASE_LOST/);
const published = await Promise.allSettled([store.completeClientDocumentDraftGeneration(publishInput), store.completeClientDocumentDraftGeneration(publishInput)]);
assert.equal(published.filter(a => a.status === 'fulfilled').length, 1);
assert.equal((await db.collection('clientApprovals').where('requestId', '==', request.id).get()).size, 1);
const updated = (await db.collection('clientRequests').doc(request.id).get()).data()!;
assert.equal(updated.status, 'waiting_client');
assert.equal(updated.draftGenerationToken, '');
pass('Draft lease expiry, stale release and atomic publication prevent duplicate drafts/approvals');
const approvalId = (await db.collection('clientApprovals').where('requestId', '==', request.id).get()).docs[0].id;
await assert.rejects(store.respondToClientApproval({ context: viewerContext, approvalId, status: 'approved' }), /CLIENT_WRITE_FORBIDDEN/);
await assert.rejects(store.respondToClientApproval({ context: otherContext, approvalId, status: 'approved' }), /CLIENT_APPROVAL_FORBIDDEN/);
const decisions = await Promise.allSettled([store.respondToClientApproval({ context, approvalId, status: 'approved' }), store.respondToClientApproval({ context, approvalId, status: 'declined' })]);
assert.equal(decisions.filter(a => a.status === 'fulfilled').length, 1);
pass('Approval decisions are scoped and single-winner');
const history = { id: 'historical', managementToken: randomUUID(), serviceId: 'routine-inspection', serviceName: 'Routine Inspection', serviceCategory: 'residential', status: 'confirmed', readinessStatus: 'ready', property: { ...propertyInput, customerEmail: owner.email, customerName: 'Owner', customerPhone: '0400000000' }, access: { method: 'vacant' }, appointment: { start: '2026-10-01T02:00:00.000Z', end: '2026-10-01T02:45:00.000Z', dateKey: '2026-10-01', dateString: '1 October 2026', timeString: '10:00', durationMinutes: 45, timezone: 'Australia/Perth' }, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() };
await db.collection('bookings').doc(history.id).set(history);
await store.getClientPortalDashboard(owner);
assert.equal((await db.collection('bookings').doc(history.id).get()).data()?.clientOrganisationId, undefined);
await assert.rejects(store.claimClientBooking({ context: otherContext, managementToken: history.managementToken }), /CLIENT_BOOKING_NOT_FOUND/);
await store.claimClientBooking({ context, managementToken: history.managementToken });
assert.equal((await db.collection('bookings').doc(history.id).get()).data()?.clientOrganisationId, context.organisation.id);
pass('Email alone cannot claim historical bookings; valid management token plus matching identity can');
const archived = await store.createClientDocument({ ...file, requestId: undefined, status: 'archived' });
assert.equal(await store.getClientDocument({ organisationId: context.organisation.id, documentId: archived.id }), null);
pass('Archived documents are unavailable to client downloads');
await db.collection('clientMemberships').doc(otherContext.membership.id).update({ status: 'revoked' });
await assert.rejects(store.ensureClientContext(other), /CLIENT_MEMBERSHIP_REVOKED/);
assert.equal((await db.collection('clientMemberships').doc(otherContext.membership.id).get()).data()?.status, 'revoked');
pass('Signing in cannot resurrect a revoked default owner membership');
await db.collection('clientUsers').doc(viewer.uid).update({ active: false });
await assert.rejects(store.ensureClientContext(viewer), /CLIENT_ACCOUNT_DISABLED/);
pass('Disabled user stays disabled through authentication');
let output = '';
const server = spawn(process.execPath, ['--import', 'tsx', 'server.ts'], { env: { ...process.env, NODE_ENV: 'production', PORT: '3101' }, stdio: ['ignore', 'pipe', 'pipe'] });
server.stdout.on('data', b => { output += b; }); server.stderr.on('data', b => { output += b; });
const base = 'http://127.0.0.1:3101';
try {
  let ready = false;
  for (let i = 0; i < 80; i++) { try { if ((await fetch(base + '/api/health')).ok) { ready = true; break; } } catch {} await new Promise(r => setTimeout(r, 250)); }
  assert.ok(ready, output);
  const headers = (token: string) => ({ Authorization: `Bearer ${token}`, 'Content-Type': 'application/json' });
  assert.equal((await fetch(base + '/api/client/dashboard')).status, 401);
  assert.equal((await fetch(base + '/api/admin/bookings', { headers: headers(owner.token) })).status, 403);
  const dashboard = await fetch(base + '/api/client/dashboard', { headers: headers(owner.token) });
  assert.equal(dashboard.status, 200);
  assert.match(dashboard.headers.get('cache-control') || '', /no-store/);
  const body = JSON.stringify(await dashboard.json());
  assert.ok(!body.includes(history.managementToken) && !body.includes('storagePath'));
  assert.equal((await fetch(base + '/api/client/dashboard', { headers: headers(other.token) })).status, 403);
  assert.equal((await fetch(base + '/api/client/dashboard', { headers: headers(viewer.token) })).status, 403);
  assert.equal((await fetch(base + '/api/client/documents/' + archived.id + '/download', { headers: headers(owner.token) })).status, 404);
  assert.equal((await fetch(base + '/api/client/bookings/claim', { method: 'POST', headers: headers(owner.token), body: '{' })).status, 400);
  pass('Real HTTP boundary rejects anonymous, client-to-admin, disabled/revoked access and malformed JSON');
} finally {
  server.kill('SIGTERM'); await once(server, 'exit').catch(() => undefined);
  writeFileSync('stage1-server.log', output);
}
console.log(`Stage 1 Client Portal: ${checks} behavioural groups passed against isolated Auth/Firestore emulators.`);
