import type { DocumentProduct } from '../types/documentRequest';

const standardResidentialDescription =
  'Preparation of the prescribed residential tenancy form for client review before distribution, with digital sending, signing and storage.';

export const DEFAULT_DOCUMENT_PRODUCTS: DocumentProduct[] = [
  {
    id: 'residential-tenancy-lease-agreement-form-1aa',
    name: 'Residential Tenancy Lease Agreement',
    formCode: 'Form 1AA',
    publicDescription: standardResidentialDescription,
    categories: ['residential'],
    priceExGst: 250,
    active: true,
    publiclyRequestable: true,
    order: 1,
    badge: 'Lease agreement',
  },
  {
    id: 'lodgement-security-bond-money-form-preparation',
    name: 'Lodgement of Security Bond Money Form Preparation',
    publicDescription: standardResidentialDescription,
    categories: ['residential'],
    priceExGst: 100,
    active: true,
    publiclyRequestable: true,
    order: 2,
  },
  {
    id: 'variation-security-bond-money-form',
    name: 'Variation of Security Bond Money Form',
    publicDescription: standardResidentialDescription,
    categories: ['residential'],
    priceExGst: 100,
    active: true,
    publiclyRequestable: true,
    order: 3,
  },
  {
    id: 'joint-application-disposal-security-bond',
    name: 'Joint Application for Disposal of Security Bond',
    publicDescription: standardResidentialDescription,
    categories: ['residential'],
    priceExGst: 100,
    active: true,
    publiclyRequestable: true,
    order: 4,
  },
  {
    id: 'notice-rent-increase-form-10',
    name: 'Notice to Tenant of Rent Increase',
    formCode: 'Form 10',
    publicDescription: standardResidentialDescription,
    categories: ['residential'],
    priceExGst: 100,
    active: true,
    publiclyRequestable: true,
    order: 5,
  },
  {
    id: 'notice-rent-increase-income-form-11',
    name: 'Notice to Tenant of Rent Increase Calculated by Tenant’s Income',
    formCode: 'Form 11',
    publicDescription: standardResidentialDescription,
    categories: ['residential'],
    priceExGst: 100,
    active: true,
    publiclyRequestable: true,
    order: 6,
  },
  {
    id: 'notice-proposed-entry-form-19',
    name: 'Notice of Proposed Entry to Premises',
    formCode: 'Form 19',
    publicDescription: standardResidentialDescription,
    categories: ['residential'],
    priceExGst: 100,
    active: true,
    publiclyRequestable: true,
    order: 7,
  },
  {
    id: 'notice-breach-agreement-form-20',
    name: 'Notice to Tenant of Breach of Agreement',
    formCode: 'Form 20',
    publicDescription: standardResidentialDescription,
    categories: ['residential'],
    priceExGst: 100,
    active: true,
    publiclyRequestable: true,
    order: 8,
  },
  {
    id: 'breach-non-payment-rent-form-21',
    name: 'Breach Notice for Non-Payment of Rent',
    formCode: 'Form 21',
    publicDescription: standardResidentialDescription,
    categories: ['residential'],
    priceExGst: 100,
    active: true,
    publiclyRequestable: true,
    order: 9,
  },
  {
    id: 'termination-family-violence-form-2',
    name: 'Notice of Termination of Tenant’s Interest in Residential Tenancy Agreement on Grounds of Family Violence',
    formCode: 'Form 2',
    publicDescription: standardResidentialDescription,
    categories: ['residential'],
    priceExGst: 100,
    active: true,
    publiclyRequestable: true,
    order: 10,
  },
  {
    id: 'termination-non-payment-rent-form-1a',
    name: 'Notice of Termination for Non-Payment of Rent',
    formCode: 'Form 1A',
    publicDescription: standardResidentialDescription,
    categories: ['residential'],
    priceExGst: 100,
    active: true,
    publiclyRequestable: true,
    order: 11,
  },
  {
    id: 'termination-non-payment-rent-form-1b',
    name: 'Notice of Termination for Non-Payment of Rent',
    formCode: 'Form 1B',
    publicDescription: standardResidentialDescription,
    categories: ['residential'],
    priceExGst: 100,
    active: true,
    publiclyRequestable: true,
    order: 12,
  },
  {
    id: 'termination-other-than-non-payment-form-1c',
    name: 'Notice of Termination Other Than Non-Payment of Rent',
    formCode: 'Form 1C',
    publicDescription: standardResidentialDescription,
    categories: ['residential'],
    priceExGst: 100,
    active: true,
    publiclyRequestable: true,
    order: 13,
  },
  {
    id: 'former-tenant-disposal-goods-form-cp2',
    name: 'Notice to Former Tenant as to Disposal of Goods',
    formCode: 'Form CP2',
    publicDescription: standardResidentialDescription,
    categories: ['residential'],
    priceExGst: 100,
    active: true,
    publiclyRequestable: true,
    order: 14,
  },
  {
    id: 'disposal-goods-form-3',
    name: 'Notice as to Disposal of Goods',
    formCode: 'Form 3',
    publicDescription: standardResidentialDescription,
    categories: ['residential'],
    priceExGst: 100,
    active: true,
    publiclyRequestable: true,
    order: 15,
  },
  {
    id: 'abandonment-premises-form-12',
    name: 'Notice to Tenants of Abandonment of Premises',
    formCode: 'Form 12',
    publicDescription: standardResidentialDescription,
    categories: ['residential'],
    priceExGst: 100,
    active: true,
    publiclyRequestable: true,
    order: 16,
  },
  {
    id: 'termination-premises-abandoned-form-13',
    name: 'Notice of Termination to Tenant if Premises Abandoned',
    formCode: 'Form 13',
    publicDescription: standardResidentialDescription,
    categories: ['residential'],
    priceExGst: 100,
    active: true,
    publiclyRequestable: true,
    order: 17,
  },
];
